development: &defaults
  vkontakte:
    app_id: 3925186
    app_secret: fSt26RSrCRicx080TKhL
  twitter:
    consumer_key: 7FnBYKLNJWDcQMFVO87Q
    consumer_secret: 0CrjoTLfG3wOQIC0avacTaF8gpgEEbKDxkAAzO4